#!/bin/python

import smtplib
 
server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login("tolga.ozaltin", "lnzxklcvgonolxoy")

subject = "SUBJECT goes here. oh yeah" 


TO="Artugrul.gazi@gmail.com,zo18376@gmail.com"

FROM="tolga.ozaltin@gmail.com"
BODY="This is the body of the email so oh yeah"
MESSAGE = "YOUR MESSAGE!  "
SUBJECT = "Subject means konu "
msg = """Subject: %s
From: %s 
To: %s
%s
""" % (SUBJECT,FROM, TO, BODY)
#server.sendmail("tolga.ozaltin@gmail.com", "dian.nostikasari@gmail.com",  msg)
server.sendmail(FROM, TO.split(",") , msg)
server.quit()






