#!/usr/bin/python
a = "lala lala asdasdsadadqd qdqdqwdqeddqewd lasdddswdqwdqwdqw"
print a
print a.replace("lala", "LAAAAAAAAAAAAAAAAA")
print a.replace("lala", "LAAAAAAAAAAAAAAAAA", 1)
print a.replace("(lala\d)", "sdsdsdsdsdsdsdsdsdsds")
print a.sub(r'la\d', "ASSASAS")
