#!/bin/python

import smtplib
 
server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login("tolga.ozaltin", "lnzxklcvgonolxoy")

subject = "SUBJECT goes here. oh yeah" 


TO="tozaltin@etcc.com"

FROM="tolga.ozaltin@gmail.com"
BODY="This is the body of the email so oh yeah GREG"
MESSAGE = "YOUR MESSAGE! GREG "
SUBJECT = "Subject means konu GREG"
msg = """Subject: %s
From: %s 
To: %s
%s
""" % (SUBJECT,FROM, TO, BODY)
#server.sendmail("tolga.ozaltin@gmail.com", "dian.nostikasari@gmail.com",  msg)
server.sendmail(FROM, TO , msg)
server.quit()











